
STAT_MODE_MINUTE = 'minute'
STAT_MODE_HOUR = 'hour'
ALLOWED_STATS_TYPES = {STAT_MODE_MINUTE, STAT_MODE_HOUR}
EVENT_TIMESTAMP_KEY = "timestamp"
HOST_REQUESTS_KEY = "host_request"
RESPONSE_ERROR_KEY = "error"
